#-Information---------------------------------------------------------------------------------------
name: ssi_stamper
category: &category Stamper
version: 1.2
target: sample
type: stamper
recommendation: required
requires_db: True
description: >
  This runs against the mondoDB database and certifies a sample that has run assemblatron and 
  whats_my_species on it's QC preformance (Core Facility/Supplying Lab/Ok). This can also be run
  as a script without output on the server (only bifrost DB)
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-ssi_stamper:1.2"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  "min_species": 0.95
  "max_unclassified": 0.2
  "contigs_max": 1500
  "average_coverage_fail": 10
  "average_coverage_low": 25
  "average_coverage_warn": 50
  "number_of_reads_fail": 10000
  "max_size_difference_for_1x_and_10x": 250000
  species_qc_value_mapping:
    "default": {"name": "default", "min_length": 1000000, "max_length": 15000000}
    "Acinetobacter baumannii": {"name": "Acinetobacter baumannii", "min_length": 3620000, "max_length": 4160000}
    "Acinetobacter pittii": {"name": "Acinetobacter pittii", "min_length": 3760000, "max_length": 4120000}
    "Actinobacillus pleuropneumoniae": {"name": "Actinobacillus pleuropneumoniae", "min_length": 2100000, "max_length": 2300000}
    "Arcanobacterium phocae": {"name": "Arcanobacterium phocae", "min_length": 1740000, "max_length": 2100000}
    "Bacillus cereus": {"name": "Bacillus cereus", "min_length": 320000, "max_length": 680000}
    "Bordetella pertussis": {"name": "Bordetella pertussis", "min_length": 2910000, "max_length": 3840000}
    "Campylobacter coli": {"name": "Campylobacter coli", "min_length": 1480000, "max_length": 1890000}
    "Campylobacter jejuni": {"name": "Campylobacter jejuni", "min_length": 1530000, "max_length": 1840000}
    "Citrobacter farmeri": {"name": "Citrobacter farmeri", "min_length": 5460000, "max_length": 5820000}
    "Citrobacter freundii": {"name": "Citrobacter freundii", "min_length": 4890000, "max_length": 5800000}
    "Clostridioides difficile": {"name": "Clostridioides difficile", "min_length": 3810000, "max_length": 4570000}
    "Clostridium botulinum": {"name": "Clostridium botulinum", "min_length": 3630000, "max_length": 3990000}
    "Clostridium butyricum": {"name": "Clostridium butyricum", "min_length": 3570000, "max_length": 3930000}
    "Clostridium perfringens": {"name": "Clostridium perfringens", "min_length": 3250000, "max_length": 3750000}
    "Corynebacterium diphtheriae": {"name": "Corynebacterium diphtheriae", "min_length": 2230000, "max_length": 2590000}
    "Cronobacter sakazakii": {"name": "Cronobacter sakazakii", "min_length": 4420000, "max_length": 4700000}
    "Enterobacter cloacae": {"name": "Enterobacter cloacae", "min_length": 5060000, "max_length": 5410000}
    "Enterococcus faecalis": {"name": "Enterococcus faecalis", "min_length": 2680000, "max_length": 3320000}
    "Enterococcus faecium": {"name": "Enterococcus faecium", "min_length": 2720000, "max_length": 3130000}
    "Escherichia coli": {"name": "Escherichia coli", "min_length": 4640000, "max_length": 5560000}
    "Haemophilus influenzae": {"name": "Haemophilus influenzae", "min_length": 1660000, "max_length": 1970000}
    "Klebsiella oxytoca": {"name": "Klebsiella oxytoca", "min_length": 5710000, "max_length": 6300000}
    "Klebsiella pneumoniae": {"name": "Klebsiella pneumoniae", "min_length": 5080000, "max_length": 5790000}
    "Klebsiella variicola": {"name": "Klebsiella variicola", "min_length": 5350000, "max_length": 6050000}
    "Legionella pneumophila": {"name": "Legionella pneumophila", "min_length": 3200000, "max_length": 3670000}
    "Listeria monocytogenes": {"name": "Listeria monocytogenes", "min_length": 2810000, "max_length": 3090000}
    "Neisseria gonorrhoeae": {"name": "Neisseria gonorrhoeae", "min_length": 1980000, "max_length": 2180000}
    "Neisseria meningitidis": {"name": "Neisseria meningitidis", "min_length": 1920000, "max_length": 2170000}
    "Pseudomonas aeruginosa": {"name": "Pseudomonas aeruginosa", "min_length": 6100000, "max_length": 7000000}
    "Salmonella enterica": {"name": "Salmonella enterica", "min_length": 4510000, "max_length": 5060000}
    "Shigella sonnei": {"name": "Shigella sonnei", "min_length": 4570000, "max_length": 4930000}
    "Staphylococcus aureus": {"name": "Staphylococcus aureus", "min_length": 2630000, "max_length": 2910000}
    "Staphylococcus capitis": {"name": "Staphylococcus capitis", "min_length": 2310000, "max_length": 2640000}
    "Staphylococcus epidermidis": {"name": "Staphylococcus epidermidis", "min_length": 2350000, "max_length": 2770000}
    "Staphylococcus lugdunensis": {"name": "Staphylococcus lugdunensis", "min_length": 2400000, "max_length": 2760000}
    "Staphylococcus pseudintermedius": {"name": "Staphylococcus pseudintermedius", "min_length": 2490000, "max_length": 2720000}
    "Staphylococcus sciuri": {"name": "Staphylococcus sciuri", "min_length": 2650000, "max_length": 3010000}
    "Staphylococcus simulans": {"name": "Staphylococcus simulans", "min_length": 2540000, "max_length": 2890000}
    "Staphylococcus xylosus": {"name": "Staphylococcus xylosus", "min_length": 5190000, "max_length": 7110000}
    "Streptococcus agalactiae": {"name": "Streptococcus agalactiae", "min_length": 1930000, "max_length": 2280000}
    "Streptococcus equi": {"name": "Streptococcus equi", "min_length": 1910000, "max_length": 2270000}
    "Streptococcus pneumoniae": {"name": "Streptococcus pneumoniae", "min_length": 1850000, "max_length": 2230000}
    "Streptococcus pseudopneumoniae": {"name": "Streptococcus pseudopneumoniae", "min_length": 1940000, "max_length": 2250000}
    "Streptococcus pyogenes": {"name": "Streptococcus pyogenes", "min_length": 1660000, "max_length": 1940000}
    "Streptococcus uberis": {"name": "Streptococcus uberis", "min_length": 1600000, "max_length": 1960000}
    "Vibrio cholerae": {"name": "Vibrio cholerae", "min_length": 3780000, "max_length": 4140000}
    "Vibrio vulnificus": {"name": "Vibrio vulnificus", "min_length": 4900000, "max_length": 5260000}
    "Yersinia aleksiciae": {"name": "Yersinia aleksiciae", "min_length": 4170000, "max_length": 4890000}
    "Yersinia enterocolitica": {"name": "Yersinia enterocolitica", "min_length": 4270000, "max_length": 5020000}
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
# None
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  component:
    assemblatron:
      status: Success
    whats_my_species:
      status: Success
#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    properties:
      stamper: # see sample_component summary
        component:
          _id: "ObjectId"
          _date: "datetime"
    stamps:
      stamp_list:
      ssi_stamper:
  sample_component:
    summary:
      test__sample__has_reads_files:
      test__species_detection__main_species_level:
      test__species_detection__unclassified_level:
      test__componenent__species_in_db:
      test__sample__species_provided_is_detected:
      test__denovo_assembly__genome_size_at_1x:
      test__denovo_assembly__genome_size_at_10x:
      test__denovo_assembly__genome_size_difference_1x_10x:
      test__denovo_assembly__genome_average_coverage:
      test__denovo_assembly__minimum_read_number:
    stamp:
      name:
      value:
      date:
#---------------------------------------------------------------------------------------------------

