# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  bifrost_db_key: "../../resources/keys.txt"

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
    maxParallel: 4

  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

#  - script: conda env create --file envs/bifrost_for_install.yaml
#    displayName: Create Anaconda environment

#  - script: source activate bifrost
#    displayName: Activate bifrost

  - script: |
      pip install . --user
    displayName: 'Install bifrostlib'
    workingDirectory: lib/bifrostlib/

  - script: |
      echo "mongodb://server.example.com:27017/serumqc_prod" > resources/keys.txt


  - script: |
      pip install pytest mongomock --user
      pip install pytest-cov --user
      pwd
      python -m pytest bifrostlib/tests --doctest-modules --junitxml=junit/test-results.xml --cov=datahandling --cov-report=xml --cov-report=html
    # pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'
    workingDirectory: lib/bifrostlib/
