# Initialization config file
# Input parameters with default values
# raw_data_folder: "raw_data" # Temporarily shelved idea to rename samples
# rename_samples: True # Temporarily shelved idea to rename samples
sample_folder: "samples"
sample_sheet: "sample_sheet.xlsx"
partition: "standard" # Default partition
#force_partition: "outbreak" # Force a slurm partition
#torque_node: # for use on specifying a torque node
grid: "slurm" # slurm|torque|none
walltime: "03:00:00"
components: "whats_my_species,assemblatron,ssi_stamper,ariba_resfinder,ariba_mlst,ariba_plasmidfinder,ariba_virulencefinder,min_read_check,qcquickie" # available options are in components directory
group: "" # group for sbatch on torque system
use_mongodb: True 
type: "project" # run type (routine, project)
read_pattern: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
samples_to_ignore: ["Undetermined"]
# samples_to_include: null
memory: &memory 10 #in Gb
threads: &threads 4
restart_times: 2
init_only: False # initialize samples but don't run the components
unlock: False # Run the components' snakemake in unlock mode (components wont run but will unlock directories)
md5skip: False # set to True to skip md5sum update when recreating samples. Recommended: False
tmp_dir: "/scratch" # Run compute intensive steps on a scratch dir to avoid overdoing IO

# --Optional override values--
# run_name: NAME                              # if provided use that for db if not use folder

# For processing sample sheets
samplesheet_column_mapping:
  sample_name: "SampleID"
  group: "SupplyingLab" 
  emails: "Initials"
  run_name: "ExperimentName"
  priority: "Priority"
  provided_species: "Organism" # a required name
  Comments: "Comments"

priority_mapping:
  high: "outbreak"
  low: "daytime"
