# Input parameters
run_folder: "samples"
sample_sheet: "sample_sheet.xlsx"
partition: "standard"
grid: "slurm" # slurm|torque|none
assembly_with: "skesa" # skesa|spades
components: "qcquickie,analysis,assembly,datadumper" # available options are in snakefiles
group: "" # group for sbatch on torque system

memory: &memory 10 #in Gb
threads: &threads 5

kraken:
  database: "/srv/data/DB/kraken/minikraken_20171019_8GB/"
  kmer_dist: "/srv/data/DB/kraken/minikraken_20171019_8GB/minikraken_8GB_100mers_distrib.txt"

abricate:
  resfinder:
    database: "/srv/data/DB/abricate/"
    name: "resfinder_db"
  plasmidfinder:
    database: "/srv/data/DB/abricate/"
    name: "plasmidfinder_db"

ariba:
  resfinder:
    database: "/srv/data/DB/ariba/resfinder"
  plasmidfinder:
    database: "/srv/data/DB/ariba/plasmidfinder"
  mlst:
    database: "/srv/data/DB/ariba/mlst/"

serum:
  read_pattern: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
  samples_to_ignore: ["Undetermined"]
  samplesheet_column_mapping:
    sample_name: "SampleID"
    group: "SupplyingLab" 
    emails: "Initials"
    run_name: "ExperimentName"
    priority: "Priority"
    provided_species: "Organism"
  database: "/home/ssi.ad/kimn/code/serumqc/DB/species_qc_values.tsv"
  minimum_number_of_reads: 10000
  qc:
    min_length: 1000
    base_depth: 1
    min_depth: 10
    recommended_depth: 25
    ambiguous_cutoff: 0.1
