#-Basic info----------------------------------------------------------------------------------------
name: cge_mlst
version: 2.0
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  category: mlst
  schema_version: 2.0
  target: sample
  type: pipeline
  recommendation: recommended
  description: >
    This preforms read based mapping against the mlst DB's. The mlst DB's are mapped against the 
    species table in mongoDB via the mlst_species_mapping variable. Multiple mlst's can be run against 
    a single species by passing all mlst's via a list (or conversely none). This is done against the 
    cge_db using kma mode. 
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-cge_mlst:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
  mlst_species_mapping:
    "Acinetobacter baumannii": [abaumannii,abaumannii_2]
    "Achromobacter": [achromobacter]
    "Aeromonas": [aeromonas]
    "Aspergillus fumigatus": [afumigatus]
    "Anaplasma phagocytophilum": [aphagocytophilum]
    "Arcobacter": [arcobacter]
    "Bartonella bacilliformis": [bbacilliformis]
    "Burkholderia cepacia complex": [bcc]
    "Bacillus cereus": [bcereus]
    "Brachyspira hampsonii": [bhampsonii]
    "Bartonella henselae": [bhenselae]
    "Brachyspira hyodysenteriae": [bhyodysenteriae]
    "Brachyspira intermedia": [bintermedia]
    "Bacillus licheniformis": [blicheniformis]
    "Bordetella pertussis": [bordetella]
    "Streptococcus pseudopneumoniae": [bordetella]
    "Borrelia": [borrelia]
    "Brachyspira pilosicoli": [bpilosicoli]
    "Burkholderia pseudomallei": [bpseudomallei]
    "Brachyspira": [brachyspira]
    "Brucella": [brucella]
    "Bacillus subtilis": [bsubtilis]
    "Candida albicans": [calbicans]
    "Campylobacter coli": [campylobacter]
    "Campylobacter jejuni": [campylobacter]
    "Clostridium botulinum": [cbotulinum]
    "Campylobacter concisus": [cconcisus]
    "Campylobacter curvus": [cconcisus]
    "Clostridioides difficile": [cdifficile]
    "Corynebacterium diphtheriae": [cdiphtheriae]
    "Campylobacter fetus": [cfetus]
    "Citrobacter freundii": [cfreundii]
    "Candida glabrata": [cglabrata]
    "Campylobacter helveticu": [chelveticus]
    "Chlamydiales": [chlamydiales]
    "Campylobacter hyointestinalis": [chyointestinalis]
    "Campylobacter insulaenigrae": [cinsulaenigrae]
    "Candidatus Liberibacter solanacearum": [liberibacter]
    "Candida krusei": [ckrusei]
    "Campylobacter lanienae": [clanienae]
    "Campylobacter lari": [clari]
    "Carnobacterium maltaromaticum": [cmaltaromaticum]
    "Cronobacter sakazakii": [cronobacter]
    "Clostridium septicum": [csepticum]
    "Clonorchis sinensis": [csinensis]
    "Campylobacter sputorum": [csputorum]
    "Candida tropicalis": [ctropicalis]
    "Campylobacter upsaliensis": [cupsaliensis]
    "Dichelobacter nodosus": [dnodosus]
    "Enterobacter cloacae": [ecloacae]
    "Escherichia coli": [ecoli,ecoli_2]
    "Edwardsiella": [edwardsiella]
    "Enterococcus faecalis": [efaecalis]
    "Enterococcus faecium": [efaecium]
    "Flavobacterium psychrophilum": [fpsychrophilum]
    "Gallibacterium anatis": [ganatis]
    "Helicobacter cinaedi": [hcinaedi]
    "Haemophilus influenzae": [hinfluenzae]
    "Haemophilus parasuis": [hparasuis]
    "Helicobacter pylori": [hpylori]
    "Helicobacter suis": [hsuis]
    "Klebsiella aerogenes": [kaerogenes]
    "Kingella kingae": [kkingae]
    "Klebsiella oxytoca": [koxytoca]
    "Klebsiella pneumoniae": [kpneumoniae]
    "Kudoa septempunctata": [kseptempunctata]
    "Leptospira": [leptospira,leptospira_2,leptospira_3]
    # llactis
    "Listeria monocytogenes": [lmonocytogenes]
    "Lactobacillus salivarius": [lsalivarius]
    "Mycobacterium abscessus": [mabscessus]
    "Mycoplasma agalactiae": [magalactiae]
    "Mycoplasma bovis": [mbovis]
    "Macrococcus canis": [mcanis]
    "Macrococcus caseolyticus": [mcaseolyticus]
    "Moraxella catarrhalis": [mcatarrhalis]
    "Mannheimia haemolytica": [mhaemolytica]
    "Mycoplasma hyopneumoniae": [mhyopneumoniae]
    "Mycoplasma hyorhinis": [mhyorhinis]
    "Mycoplasma iowae": [miowae]
    "Mycobacterium massiliense": [mmassiliense]
    "Melissococcus plutonius": [mplutonius]
    "Mycoplasma pneumoniae": [mpneumoniae]
    "Mycoplasma synoviae": [msynoviae]
    "Mycobacteria": [mycobacteria]
    "Neisseria gonorrhoeae": [neisseria]
    "Neisseria meningitidis": [neisseria]
    "Ornithobacterium rhinotracheale": [orhinotracheale]
    "Orientia tsutsugamushi": [otsutsugamushi]
    "Propionibacterium acnes": [pacnes]
    "Pseudomonas aeruginosa": [paeruginosa]
    "Photobacterium damselae": [pdamselae]
    "Pseudomonas fluorescens": [pfluorescens]
    "Porphyromonas gingivalis": [pgingivalis]
    "Paenibacillus larvae": [plarvae]
    "Pasteurella multocida": [pmultocida_multihost,pmultocida_rirdc]
    "Pediococcus pentosaceus": [ppentosaceus]
    "Pseudomonas putida": [pputida]
    "Piscirickettsia salmonis": [psalmonis]
    "Riemerella anatipestifer": [ranatipestifer]
    "Rhodococcus": [rhodococcus]
    "Streptococcus agalactiae": [sagalactiae]
    "Staphylococcus aureus": [saureus]
    "Streptococcus bovis equinus complex_ SBSEC": [sbsec]
    "Streptococcus canis": [scanis]
    "Streptococcus dysgalactiae equisimilis": [sdysgalactiae]
    "Salmonella enterica": [senterica]
    "Staphylococcus epidermidis": [sepidermidis]
    "Streptococcus gallolyticus": [sgallolyticus]
    "Staphylococcus haemolyticus": [shaemolyticus]
    "Stapylococcus hominis": [shominis]
    "Sinorhizobium": [sinorhizobium]
    "Staphylococcus lugdunensis": [slugdunensis]
    "Stenotrophomonas maltophilia": [smaltophilia]
    "Streptococcus oralis": [soralis]
    "Saprolegnia parasitica": [sparasitica]
    "Streptococcus pneumoniae": [spneumoniae]
    "Staphylococcus pseudintermedius": [spseudintermedius]
    "Streptococcus pyogenes": [spyogenes]
    "Streptococcus suis": [ssuis]
    "Streptococcus thermophilus": [sthermophilus,sthermophilus_2]
    "Streptomyces": [streptomyces]
    "Streptococcus uberis": [suberis]
    "Streptococcus zooepidemicus": [szooepidemicus]
    "Taylorella": [taylorella]
    "Tenacibaculum": [tenacibaculum]
    "Treponema pallidum": [tpallidum]
    "Trichomonas vaginalis": [tvaginalis]
    "Ureaplasma": [ureaplasma]
    "Vibrio cholerae": [vcholerae,vcholerae2]
    "Vibrio": [vibrio]
    "Vibrio parahaemolyticus": [vparahaemolyticus]
    "Vibrio tapetis": [vtapetis]
    "Vibrio vulnificus": [vvulnificus]
    "Wolbachia": [wolbachia]
    "Xylella fastidiosa": [xfastidiosa]
    "Yersinia aleksiciae": [yersinia]
    "Yersinia enterocolitica": [yersinia]
    "Yersinia pseudotuberculosis": [ypseudotuberculosis]
    "Yersinia ruckeri": [yruckeri]
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  database_path: "/bifrost_resources/mlst_db"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      datafiles:
        paired_reads:
      species_detection:
        summary:
          species:
            - Acinetobacter baumannii
            - Achromobacter
            - Aeromonas
            - Aspergillus fumigatus
            - Anaplasma phagocytophilum
            - Arcobacter
            - Bartonella bacilliformis
            - Burkholderia cepacia complex
            - Bacillus cereus
            - Brachyspira hampsonii
            - Bartonella henselae
            - Brachyspira hyodysenteriae
            - Brachyspira intermedia
            - Bacillus licheniformis
            - Bordetella pertussis
            - Streptococcus pseudopneumoniae
            - Borrelia
            - Brachyspira pilosicoli
            - Burkholderia pseudomallei
            - Brachyspira
            - Brucella
            - Bacillus subtilis
            - Candida albicans
            - Campylobacter coli
            - Campylobacter jejuni
            - Clostridium botulinum
            - Campylobacter concisus
            - Campylobacter curvus
            - Clostridioides difficile
            - Corynebacterium diphtheriae
            - Campylobacter fetus
            - Citrobacter freundii
            - Candida glabrata
            - Campylobacter helveticu
            - Chlamydiales
            - Campylobacter hyointestinalis
            - Campylobacter insulaenigrae
            - Candidatus Liberibacter solanacearum
            - Candida krusei
            - Campylobacter lanienae
            - Campylobacter lari
            - Carnobacterium maltaromaticum
            - Cronobacter sakazakii
            - Clostridium septicum
            - Clonorchis sinensis
            - Campylobacter sputorum
            - Candida tropicalis
            - Campylobacter upsaliensis
            - Dichelobacter nodosus
            - Enterobacter cloacae
            - Escherichia coli
            - Edwardsiella
            - Enterococcus faecalis
            - Enterococcus faecium
            - Flavobacterium psychrophilum
            - Gallibacterium anatis
            - Helicobacter cinaedi
            - Haemophilus influenzae
            - Haemophilus parasuis
            - Helicobacter pylori
            - Helicobacter suis
            - Klebsiella aerogenes
            - Kingella kingae
            - Klebsiella oxytoca
            - Klebsiella pneumoniae
            - Kudoa septempunctata
            - Leptospira
            - Listeria monocytogenes
            - Lactobacillus salivarius
            - Mycobacterium abscessus
            - Mycoplasma agalactiae
            - Mycoplasma bovis
            - Macrococcus canis
            - Macrococcus caseolyticus
            - Moraxella catarrhalis
            - Mannheimia haemolytica
            - Mycoplasma hyopneumoniae
            - Mycoplasma hyorhinis
            - Mycoplasma iowae
            - Mycobacterium massiliense
            - Melissococcus plutonius
            - Mycoplasma pneumoniae
            - Mycoplasma synoviae
            - Mycobacteria
            - Neisseria gonorrhoeae
            - Neisseria meningitidis
            - Ornithobacterium rhinotracheale
            - Orientia tsutsugamushi
            - Propionibacterium acnes
            - Pseudomonas aeruginosa
            - Photobacterium damselae
            - Pseudomonas fluorescens
            - Porphyromonas gingivalis
            - Paenibacillus larvae
            - Pasteurella multocida
            - Pediococcus pentosaceus
            - Pseudomonas putida
            - Piscirickettsia salmonis
            - Riemerella anatipestifer
            - Rhodococcus
            - Streptococcus agalactiae
            - Staphylococcus aureus
            - Streptococcus bovis equinus complex_ SBSEC
            - Streptococcus canis
            - Streptococcus dysgalactiae equisimilis
            - Salmonella enterica
            - Staphylococcus epidermidis
            - Streptococcus gallolyticus
            - Staphylococcus haemolyticus
            - Stapylococcus hominis
            - Sinorhizobium
            - Staphylococcus lugdunensis
            - Stenotrophomonas maltophilia
            - Streptococcus oralis
            - Saprolegnia parasitica
            - Streptococcus pneumoniae
            - Staphylococcus pseudintermedius
            - Streptococcus pyogenes
            - Streptococcus suis
            - Streptococcus thermophilus
            - Streptomyces
            - Streptococcus uberis
            - Streptococcus zooepidemicus
            - Taylorella
            - Tenacibaculum
            - Treponema pallidum
            - Trichomonas vaginalis
            - Ureaplasma
            - Vibrio cholerae
            - Vibrio
            - Vibrio parahaemolyticus
            - Vibrio tapetis
            - Vibrio vulnificus
            - Wolbachia
            - Xylella fastidiosa
            - Yersinia aleksiciae
            - Yersinia enterocolitica
            - Yersinia pseudotuberculosis
            - Yersinia ruckeri
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: []
  sample:
    properties:
      mlst:
        summary:  # see sample_component summary
        component:
          _id: 
          date:  # ObjectId
    report:
      mlst:
        title: "MLST"
        info: *dockerfile
        columns: 
          - {id: "db", name: "db"}
          - {id: "strain", name: "strain"}
          - {id: "alleles", name: "alleles"}
        data: []
  sample_component:
    summary:
      strain:  # str for mlst_db
    results:
      cge_mlst/data_yaml: {}
#---------------------------------------------------------------------------------------------------
