#-Information---------------------------------------------------------------------------------------
name: ariba_plasmidfinder
version: 1.0
target: sample
type: pipeline
recommendation: recommended
description: >
  This preforms read based mapping against the plasmidfinder DB's. 
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# -None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
abricate_plasmidfinder_database: "/srv/data/DB/abricate/plasmidfinder_db/" 
ariba_plasmidfinder_database: "/srv/data/DB/ariba/plasmidfinder_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  # None
#---------------------------------------------------------------------------------------------------