#-Information---------------------------------------------------------------------------------------
name: ariba_resfinder
category: resistance
version: 2.0
schema_version: 2.0
target: sample
type: pipeline
recommendation: recommended
requires_db: True
description: >
  This preforms read based mapping against the resfinder DB's. The options show the species entries 
  which will be attempted for mlst with key originating from the species DB. This is done against 
  the cge_db using ariba.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: &dockerfile "docker://ssidk/bifrost-ariba_resfinder:2.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
options:
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path, a recommended
# strategy for shrared resources is to symlink the resource from the root resources folder into
# the component resources folder. This will prevent
database_path: "/bifrost_resources/resfinder/ref_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  files: ["report.tsv"]
  sample:
    properties:
      resistance:
        component:
          _id: "ObjectId"
          _date: "datetime"
    reporter:
      resistance:
        title: Resistance
        info: *dockerfile
        content: [["gene", "%cov", "%id", "# of variants"]]  # headers
  sample_component:
    summary:
#---------------------------------------------------------------------------------------------------
