default:
  min_length: 1000000
  max_length: 15000000
  max_contigs: 1000
  coverage_base: 0
  coverage_compare: 25
  lack_of_reads_cov: 10
  not_enough_reads_cov: 25
  low_reads_cov: 50
  max_genuses: 1
  allowable_percent_unclassified: 100
  length_difference: 250000
  contig_difference: 1000
  comment: use these values if another isn't given
A. baumannii: