#-Information---------------------------------------------------------------------------------------
name: whats_my_species
version: 1.0
target: sample
type: pipeline
recommendation: required
description: >
  This runs kraken/bracken on a sample in order to determine the species found in the sample. Reads
  are first filtered using bbduk. The species is then set for the sample from this.
#---------------------------------------------------------------------------------------------------

#-Docker location-----------------------------------------------------------------------------------
dockerfile: "docker://jkimleeng/bifrost-whats_my_species:1.0"
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path.
# Note paths are set up to the absolute locations in the docker container, if you want 
# to overwrite these values be sure to mount the src folder to the docker image
kraken_database: "/bifrost_resources/minikraken_20171019_8GB/"
kraken_kmer_dist: "/bifrost_resources/minikraken_8GB_100mers_distrib.txt"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
#-DB Value changes (excluding component output)-----------------------------------------------------
db_values_changes:
  sample:
    properties:
      species:
#---------------------------------------------------------------------------------------------------

