#-Information---------------------------------------------------------------------------------------
name: ariba_virulencefinder
version: 1.1
target: sample
type: pipeline
recommendation: recommended
description: >
  This preforms read based mapping against the virulencefinder DB's.
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# -None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
abricate_virulencefinder_database: "resources/abricate_virulencefinder_db/" 
ariba_virulencefinder_database: "resources/ariba_virulencefinder_db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    reads:
      R1:
      R2:
    properties:
      provided_species: ['Escherichia coli', 'Staphylococcus aureus', 'Listeria monocytogenes', 'Enterococcus faecium']
#-DB Value changes (excluding component output)-----------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------
