#-Information---------------------------------------------------------------------------------------
name: ariba_mlst
version: 1.1
target: sample
type: pipeline
recommendation: recommended
requires_db: True
description: >
  This preforms read based mapping against the mlst DB's. The mlst DB's are set via the species 
  table in the mongoDB. This was previously a part of Analyzer, but is better maintained by 
  splitting that component apart
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
# None
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
# Relative files are relative to this components folder if not using an absolute path
mlst_database_path: "/home/projects/ssi_10003/data/DB/ariba/mlst/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    properties:
      species:
#---------------------------------------------------------------------------------------------------