name: Build and push Docker images to Dockerhub
on:
  push:
  release:
    types: [created]

jobs:
    build-n-publish:
      name: Publish Docker üê≥ image üì¶ to Dockerhub
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images (to dev)
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tags: dev
      - name: Build and push Docker images (to latest)
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tags: latest
      - name: Build and push Docker images (to version)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # optional
          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          repository: ssidk/${{ github.event.repository.name }}
          tag_with_ref: true # optional
          push: ${{ startsWith(github.ref, 'refs/tags/') }} # composite of code_version__resource_version